@host = {{$dotenv HOST}}:{{$dotenv PORT}}
@json = application/json

# @name root
GET / 
Host: {{host}}
Accept: {{json}}
###

# @name health
GET /health 
Host: {{host}}
Accept: {{json}}
###

# @name register
POST /auth/register
Host: {{host}}
Accept: {{json}}
Content-Type: {{json}}

{
    "email": "na@sutu.as",
    "password": "bxnb5e0ovi",
    "passwordConfirmation": "bxnb5e0ovi"
}
###

# @name login
POST /auth/login
Host: {{host}}
Accept: {{json}}
Content-Type: {{json}}

{
    "email": "fu@cijed.cg",
    "password": "bxnb5e0ovi"
}
###